@startuml

node "System" as app
node "API Banco do Brasil" as api

queue "Raw Data Topic" as rawDataT
queue "Normalized Data Topic" as normalizedDataT

node "Normalization Stream" as ns

database "Database" as db

app             ->  api : Consume
rawDataT        <-- app
ns              ->  rawDataT
ns              --> normalizedDataT
normalizedDataT ->  app
app             --> db


@enduml