@startuml

node     "System"                as s #LightBlue
node     "API Banco do Brasil"   as api #Yellow
queue    "Raw Data Topic"        as rawDataT #LightGreen
queue    "Normalized Data Topic" as normalizedDataT #LightGreen
queue    "Dead Letter Topic"     as dlq #LightGreen
node     "Normalization Stream"  as ns #LightBlue
database "Database"              as db #LightGreen

s               <->           api : Consume
rawDataT        <--          s : Publish raw data
ns              <-           rawDataT : Consume
ns              -->          normalizedDataT : Publish normalized data
normalizedDataT ->           s : Consume
s               -->          db : Save on database
dlq             <-           ns : Publish error
normalizedDataT -[hidden]--> dlq
dlq <-> s : Publish error

@enduml