@startuml
left to right direction

actor "Usuario" as u

package Sistema {
    usecase "Cadastrar prefeitura" as cp #LightBlue
    usecase "Cadastrar grupo de prefeituras" as cgp #LightBlue
    usecase "Gerar relatórios de arrecadações" as gra #LightBlue
}

u --> cp
u --> cgp
u --> gra

@enduml